#!/bin/bash

BASE_DIR="$HOME/MediaCenter"

DASHBOARD_DIR="$BASE_DIR/Dashboard"
DASHBOARD_SCRIPT="$DASHBOARD_DIR/dashboard.sh"

STREAMING_DIR="$BASE_DIR/Streaming"
GAMING_DIR="$BASE_DIR/Gaming"
SECURITY_DIR="$BASE_DIR/Security"
UTILITIES_DIR="$BASE_DIR/Utilities"
SETTINGS_DIR="$BASE_DIR/Settings"

CONFIG_DIR="$BASE_DIR/Configs"
LOG_DIR="$BASE_DIR/Logs"
INSTALLER_DIR="$BASE_DIR/Installer"
CONTROLLER_DIR="$CONFIG_DIR/Controllers"